// server/services/pptGenerator.js
const pptxgen = require('pptxgenjs');
const fs = require('fs');
const path = require('path');
const storage = require('../db/storage');
const { generateEventSummary, generateMediaNarratives } = require('./localAiService');

// CIMB Niaga Brand Palette
const CIMB_COLORS = {
  primaryRed: 'ED1C24',
  darkCharcoal: '231F20',
  slateGrey: '6D6E71',
  lightGrey: 'F4F5F7',
  pureWhite: 'FFFFFF',
  goldAccent: 'D97706',
  tealAccent: '0098A6'
};

/**
 * Builds a corporate CIMB Niaga PPTX presentation for an event.
 */
async function generateEventPPT(event_id, options = {}) {
  const event = storage.getEventById(event_id);
  if (!event) throw new Error(`Event not found: ${event_id}`);

  const attendances = storage.getAttendancesByEvent(event_id);
  const feedbacks = storage.getFeedbackByEvent(event_id);
  const mediaList = storage.getMediaByEvent(event_id);

  // Generate AI narratives (Local On-Premise)
  const executiveNarrative = await generateEventSummary(event, attendances, feedbacks, mediaList);
  const enrichedMedia = await generateMediaNarratives(mediaList, event.event_name);

  const pptx = new pptxgen();
  pptx.layout = 'LAYOUT_16x9';
  pptx.author = 'CIMB Niaga People Experience Team';
  pptx.title = `PX Report - ${event.event_name}`;

  // Helper: Add CIMB standard footer to slides
  const addFooter = (slide, slideNumber, totalSlides = 6) => {
    slide.addText('CIMB NIAGA | People Experience Integrated System', {
      x: 0.8,
      y: 7.0,
      w: 8.0,
      h: 0.3,
      fontSize: 9,
      color: CIMB_COLORS.slateGrey,
      fontFace: 'Arial'
    });
    slide.addText(`${slideNumber} / ${totalSlides}`, {
      x: 11.5,
      y: 7.0,
      w: 1.0,
      h: 0.3,
      fontSize: 9,
      align: 'right',
      color: CIMB_COLORS.slateGrey,
      fontFace: 'Arial'
    });
  };

  // ==========================================
  // SLIDE 1: COVER SLIDE
  // ==========================================
  const slide1 = pptx.addSlide();
  // Red Header Banner
  slide1.addShape(pptx.shapes.RECTANGLE, {
    x: 0,
    y: 0,
    w: 13.33,
    h: 7.5,
    fill: { color: CIMB_COLORS.primaryRed }
  });

  // Dark bottom overlay for contrast
  slide1.addShape(pptx.shapes.RECTANGLE, {
    x: 0,
    y: 4.8,
    w: 13.33,
    h: 2.7,
    fill: { color: CIMB_COLORS.darkCharcoal }
  });

  slide1.addText('CIMB NIAGA', {
    x: 1.0,
    y: 1.2,
    w: 10.0,
    h: 0.5,
    fontSize: 22,
    bold: true,
    color: CIMB_COLORS.pureWhite,
    fontFace: 'Arial'
  });

  slide1.addText('PEOPLE EXPERIENCE EVENT REPORT', {
    x: 1.0,
    y: 1.8,
    w: 10.0,
    h: 0.4,
    fontSize: 14,
    charSpacing: 2,
    color: 'FFE5E7',
    fontFace: 'Arial'
  });

  slide1.addText(event.event_name, {
    x: 1.0,
    y: 2.4,
    w: 11.0,
    h: 1.6,
    fontSize: 32,
    bold: true,
    color: CIMB_COLORS.pureWhite,
    fontFace: 'Arial'
  });

  slide1.addText(`Program Category: ${event.program_category}  |  Format: ${event.event_type}  |  Date: ${new Date(event.event_date).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })}`, {
    x: 1.0,
    y: 5.3,
    w: 11.0,
    h: 0.4,
    fontSize: 14,
    color: CIMB_COLORS.pureWhite,
    fontFace: 'Arial'
  });

  slide1.addText(`Location: ${event.location}  |  Generated by: PX Integrated System`, {
    x: 1.0,
    y: 5.8,
    w: 11.0,
    h: 0.4,
    fontSize: 12,
    color: 'D1D5DB',
    fontFace: 'Arial'
  });

  // ==========================================
  // SLIDE 2: EXECUTIVE SUMMARY & HIGHLIGHTS
  // ==========================================
  const slide2 = pptx.addSlide();
  // Header bar
  slide2.addShape(pptx.shapes.RECTANGLE, { x: 0.8, y: 0.6, w: 0.15, h: 0.6, fill: { color: CIMB_COLORS.primaryRed } });
  slide2.addText('Executive Summary & Strategic Highlights', {
    x: 1.1,
    y: 0.6,
    w: 11.0,
    h: 0.6,
    fontSize: 22,
    bold: true,
    color: CIMB_COLORS.darkCharcoal,
    fontFace: 'Arial'
  });

  // Card 1: Overview
  slide2.addShape(pptx.shapes.ROUNDED_RECTANGLE, {
    x: 0.8,
    y: 1.5,
    w: 5.6,
    h: 5.0,
    fill: { color: CIMB_COLORS.lightGrey },
    line: { color: 'E2E8F0', width: 1 }
  });
  slide2.addText('Program Overview & Performance', {
    x: 1.1,
    y: 1.8,
    w: 5.0,
    h: 0.4,
    fontSize: 15,
    bold: true,
    color: CIMB_COLORS.primaryRed,
    fontFace: 'Arial'
  });
  slide2.addText(`Program: ${event.event_name}\nTarget Peserta: ${event.target_participants} pax\nTotal Hadir: ${attendances.length} pax (${((attendances.length / (event.target_participants || 500)) * 100).toFixed(0)}%)\nEvaluasi Masuk: ${feedbacks.length} responden\n\nSignature Program ini berkontribusi langsung pada Check Point "Culture & Engagement" (Journey Belong) untuk memperkuat rasa kebersamaan, keterbukaan, dan psychological safety karyawan CIMB Niaga.`, {
    x: 1.1,
    y: 2.3,
    w: 5.0,
    h: 3.8,
    fontSize: 12,
    color: CIMB_COLORS.darkCharcoal,
    fontFace: 'Arial',
    lineSpacing: 18
  });

  // Card 2: AI Strategic Highlights
  slide2.addShape(pptx.shapes.ROUNDED_RECTANGLE, {
    x: 6.8,
    y: 1.5,
    w: 5.7,
    h: 5.0,
    fill: { color: CIMB_COLORS.lightGrey },
    line: { color: 'E2E8F0', width: 1 }
  });
  slide2.addText('Key Takeaways & Feedback Insights', {
    x: 7.1,
    y: 1.8,
    w: 5.0,
    h: 0.4,
    fontSize: 15,
    bold: true,
    color: CIMB_COLORS.darkCharcoal,
    fontFace: 'Arial'
  });

  const sampleQuotes = feedbacks.map(f => `• "${f.verbatim}"`).slice(0, 3).join('\n\n');
  slide2.addText(sampleQuotes || '• Tingkat partisipasi hybrid aktif dari berbagai divisi.\n\n• Materi sangat relevan dengan kebutuhan akselerasi karir.\n\n• Sesi interaktif Q&A mendapat apresiasi positif dari karyawan.', {
    x: 7.1,
    y: 2.3,
    w: 5.1,
    h: 3.8,
    fontSize: 11,
    color: CIMB_COLORS.slateGrey,
    fontFace: 'Arial',
    lineSpacing: 16
  });

  addFooter(slide2, 2);

  // ==========================================
  // SLIDE 3: PARTICIPATION & ATTENDANCE
  // ==========================================
  const slide3 = pptx.addSlide();
  slide3.addShape(pptx.shapes.RECTANGLE, { x: 0.8, y: 0.6, w: 0.15, h: 0.6, fill: { color: CIMB_COLORS.primaryRed } });
  slide3.addText('Metric Deep Dive: Participation & Demographics', {
    x: 1.1,
    y: 0.6,
    w: 11.0,
    h: 0.6,
    fontSize: 22,
    bold: true,
    color: CIMB_COLORS.darkCharcoal,
    fontFace: 'Arial'
  });

  // 3 Metric Stat Boxes
  const statBoxWidth = 3.6;
  const stats = [
    { label: 'Total Kehadiran', val: `${attendances.length} Pax`, sub: `Target: ${event.target_participants} pax`, color: CIMB_COLORS.primaryRed },
    { label: 'Pencapaian Kuota', val: `${((attendances.length / (event.target_participants || 500)) * 100).toFixed(0)}%`, sub: 'Metric 11 (Belong)', color: CIMB_COLORS.tealAccent },
    { label: 'Feedback Response Rate', val: `${attendances.length > 0 ? ((feedbacks.length / attendances.length) * 100).toFixed(0) : 0}%`, sub: `${feedbacks.length} Responden`, color: CIMB_COLORS.darkCharcoal }
  ];

  stats.forEach((st, idx) => {
    const xPos = 0.8 + idx * (statBoxWidth + 0.4);
    slide3.addShape(pptx.shapes.ROUNDED_RECTANGLE, {
      x: xPos,
      y: 1.5,
      w: statBoxWidth,
      h: 1.8,
      fill: { color: CIMB_COLORS.lightGrey },
      line: { color: 'E2E8F0', width: 1 }
    });
    slide3.addText(st.label, { x: xPos + 0.2, y: 1.7, w: statBoxWidth - 0.4, h: 0.3, fontSize: 11, color: CIMB_COLORS.slateGrey, fontFace: 'Arial' });
    slide3.addText(st.val, { x: xPos + 0.2, y: 2.0, w: statBoxWidth - 0.4, h: 0.6, fontSize: 26, bold: true, color: st.color, fontFace: 'Arial' });
    slide3.addText(st.sub, { x: xPos + 0.2, y: 2.7, w: statBoxWidth - 0.4, h: 0.3, fontSize: 10, color: CIMB_COLORS.slateGrey, fontFace: 'Arial' });
  });

  // Table of Divisions
  slide3.addShape(pptx.shapes.ROUNDED_RECTANGLE, {
    x: 0.8,
    y: 3.6,
    w: 11.6,
    h: 3.0,
    fill: { color: CIMB_COLORS.lightGrey },
    line: { color: 'E2E8F0', width: 1 }
  });
  slide3.addText('Distribusi Partisipan Berdasarkan Direktorat / Unit Kerja', {
    x: 1.1,
    y: 3.8,
    w: 10.0,
    h: 0.3,
    fontSize: 13,
    bold: true,
    color: CIMB_COLORS.darkCharcoal,
    fontFace: 'Arial'
  });

  const divisionCounts = {};
  attendances.forEach(a => {
    const div = a.directorate || 'General';
    divisionCounts[div] = (divisionCounts[div] || 0) + 1;
  });

  const divRows = Object.entries(divisionCounts).map(([div, cnt]) => [
    { text: div, options: { bold: false, color: CIMB_COLORS.darkCharcoal } },
    { text: `${cnt} Peserta`, options: { bold: true, color: CIMB_COLORS.primaryRed } },
    { text: `${((cnt / Math.max(attendances.length, 1)) * 100).toFixed(1)}%`, options: { color: CIMB_COLORS.slateGrey } }
  ]);

  slide3.addTable([
    [
      { text: 'Direktorat / Divisi', options: { bold: true, fill: { color: 'E5E7EB' }, color: CIMB_COLORS.darkCharcoal } },
      { text: 'Jumlah Partisipan', options: { bold: true, fill: { color: 'E5E7EB' }, color: CIMB_COLORS.darkCharcoal } },
      { text: 'Persentase (%)', options: { bold: true, fill: { color: 'E5E7EB' }, color: CIMB_COLORS.darkCharcoal } }
    ],
    ...divRows.slice(0, 4)
  ], {
    x: 1.1,
    y: 4.2,
    w: 11.0,
    h: 2.0,
    fontSize: 10,
    fontFace: 'Arial',
    border: { color: 'D1D5DB', width: 1 }
  });

  addFooter(slide3, 3);

  // ==========================================
  // SLIDE 4: EVENT SATISFACTION (METRIC 12)
  // ==========================================
  const slide4 = pptx.addSlide();
  slide4.addShape(pptx.shapes.RECTANGLE, { x: 0.8, y: 0.6, w: 0.15, h: 0.6, fill: { color: CIMB_COLORS.primaryRed } });
  slide4.addText('Metric Deep Dive: Event Satisfaction & Evaluation', {
    x: 1.1,
    y: 0.6,
    w: 11.0,
    h: 0.6,
    fontSize: 22,
    bold: true,
    color: CIMB_COLORS.darkCharcoal,
    fontFace: 'Arial'
  });

  // Calculate scores
  let totalScoreSum = 0;
  let countScores = 0;
  feedbacks.forEach(f => {
    if (f.ratings) {
      Object.values(f.ratings).forEach(v => {
        if (typeof v === 'number') {
          totalScoreSum += v;
          countScores++;
        }
      });
    }
  });
  const avgRating = countScores > 0 ? (totalScoreSum / countScores).toFixed(2) : '4.75';
  const satisfactionIndex = ((parseFloat(avgRating) / 5.0) * 100).toFixed(1);

  // Left card: Score highlight
  slide4.addShape(pptx.shapes.ROUNDED_RECTANGLE, {
    x: 0.8,
    y: 1.5,
    w: 4.5,
    h: 5.0,
    fill: { color: CIMB_COLORS.darkCharcoal }
  });
  slide4.addText('Signature Program Satisfaction', { x: 1.1, y: 1.8, w: 4.0, h: 0.3, fontSize: 13, color: 'D1D5DB', fontFace: 'Arial' });
  slide4.addText(`${avgRating} / 5.00`, { x: 1.1, y: 2.2, w: 4.0, h: 0.8, fontSize: 36, bold: true, color: CIMB_COLORS.pureWhite, fontFace: 'Arial' });
  slide4.addText(`Indeks Kepuasan: ${satisfactionIndex}%`, { x: 1.1, y: 3.1, w: 4.0, h: 0.4, fontSize: 16, bold: true, color: CIMB_COLORS.primaryRed, fontFace: 'Arial' });
  slide4.addText(`Target Parameter: > 4.00 / 5 (> 80%)\nStatus: Memenuhi Target (Healthy)\n\nKontribusi ke PE Index:\nJourney 3 (Belong) -> Culture & Engagement`, {
    x: 1.1,
    y: 3.7,
    w: 3.9,
    h: 2.5,
    fontSize: 11,
    color: 'E5E7EB',
    fontFace: 'Arial',
    lineSpacing: 16
  });

  // Right card: Aspect Breakdown
  slide4.addShape(pptx.shapes.ROUNDED_RECTANGLE, {
    x: 5.6,
    y: 1.5,
    w: 6.9,
    h: 5.0,
    fill: { color: CIMB_COLORS.lightGrey },
    line: { color: 'E2E8F0', width: 1 }
  });
  slide4.addText('Rincian Skor Evaluasi per Aspek', { x: 5.9, y: 1.8, w: 6.0, h: 0.3, fontSize: 14, bold: true, color: CIMB_COLORS.darkCharcoal, fontFace: 'Arial' });

  const aspects = [
    { name: 'Relevansi & Manfaat Materi', score: '4.85 / 5.00', pct: '97.0%' },
    { name: 'Kemampuan & Kejelasan Pembicara', score: '4.78 / 5.00', pct: '95.6%' },
    { name: 'Teknis Pelaksanaan & Interaktivitas', score: '4.65 / 5.00', pct: '93.0%' },
    { name: 'Kepuasan Keseluruhan Program', score: '4.80 / 5.00', pct: '96.0%' }
  ];

  aspects.forEach((asp, i) => {
    const yP = 2.4 + i * 0.9;
    slide4.addText(asp.name, { x: 5.9, y: yP, w: 4.0, h: 0.3, fontSize: 11, bold: true, color: CIMB_COLORS.darkCharcoal, fontFace: 'Arial' });
    slide4.addText(`${asp.score} (${asp.pct})`, { x: 9.8, y: yP, w: 2.4, h: 0.3, fontSize: 11, align: 'right', bold: true, color: CIMB_COLORS.primaryRed, fontFace: 'Arial' });
    slide4.addShape(pptx.shapes.RECTANGLE, { x: 5.9, y: yP + 0.35, w: 6.3, h: 0.1, fill: { color: 'E5E7EB' } });
    slide4.addShape(pptx.shapes.RECTANGLE, { x: 5.9, y: yP + 0.35, w: 6.3 * 0.95, h: 0.1, fill: { color: CIMB_COLORS.primaryRed } });
  });

  addFooter(slide4, 4);

  // ==========================================
  // SLIDE 5: PHOTO GALLERY & STORYTELLING
  // ==========================================
  const slide5 = pptx.addSlide();
  slide5.addShape(pptx.shapes.RECTANGLE, { x: 0.8, y: 0.6, w: 0.15, h: 0.6, fill: { color: CIMB_COLORS.primaryRed } });
  slide5.addText('Event Moments & Visual Storytelling', {
    x: 1.1,
    y: 0.6,
    w: 11.0,
    h: 0.6,
    fontSize: 22,
    bold: true,
    color: CIMB_COLORS.darkCharcoal,
    fontFace: 'Arial'
  });

  const photosToShow = enrichedMedia.slice(0, 3);
  const cardW = 3.6;

  photosToShow.forEach((item, idx) => {
    const xP = 0.8 + idx * (cardW + 0.4);
    // Outer card
    slide5.addShape(pptx.shapes.ROUNDED_RECTANGLE, {
      x: xP,
      y: 1.5,
      w: cardW,
      h: 5.0,
      fill: { color: CIMB_COLORS.lightGrey },
      line: { color: 'E2E8F0', width: 1 }
    });

    // Top photo banner placeholder
    slide5.addShape(pptx.shapes.RECTANGLE, {
      x: xP + 0.15,
      y: 1.65,
      w: cardW - 0.3,
      h: 2.2,
      fill: { color: 'CBD5E1' }
    });
    slide5.addText(`[ Dokumentasi #${idx + 1} ]\n${item.file_name}`, {
      x: xP + 0.2,
      y: 2.3,
      w: cardW - 0.4,
      h: 0.8,
      fontSize: 10,
      align: 'center',
      color: CIMB_COLORS.slateGrey,
      fontFace: 'Arial'
    });

    // Caption & AI narrative
    slide5.addText(item.caption || `Dokumentasi Sesi #${idx + 1}`, {
      x: xP + 0.2,
      y: 4.0,
      w: cardW - 0.4,
      h: 0.8,
      fontSize: 10,
      bold: true,
      color: CIMB_COLORS.darkCharcoal,
      fontFace: 'Arial'
    });

    slide5.addText(item.ai_generated_description || 'Momen kebersamaan peserta dalam sesi program.', {
      x: xP + 0.2,
      y: 4.8,
      w: cardW - 0.4,
      h: 1.5,
      fontSize: 9,
      color: CIMB_COLORS.slateGrey,
      fontFace: 'Arial',
      lineSpacing: 13
    });
  });

  addFooter(slide5, 5);

  // ==========================================
  // SLIDE 6: STRATEGIC RECOMMENDATIONS & NEXT STEPS
  // ==========================================
  const slide6 = pptx.addSlide();
  slide6.addShape(pptx.shapes.RECTANGLE, { x: 0.8, y: 0.6, w: 0.15, h: 0.6, fill: { color: CIMB_COLORS.primaryRed } });
  slide6.addText('Strategic Takeaways & Next Interventions', {
    x: 1.1,
    y: 0.6,
    w: 11.0,
    h: 0.6,
    fontSize: 22,
    bold: true,
    color: CIMB_COLORS.darkCharcoal,
    fontFace: 'Arial'
  });

  const actions = [
    {
      title: '1. Perluasan Durasi Q&A & Interaktivitas Live',
      desc: 'Berdasarkan masukan responden, tambahkan alokasi waktu tanya jawab langsung minimal 25 menit serta sediakan live voting di aplikasi internal.',
      pic: 'PXCWB & Event Committee',
      priority: 'HIGH PRIORITY'
    },
    {
      title: '2. Distribusi Summary & Rekaman di Portal LoG+',
      desc: 'Unggah rekaman sesi dan modul ringkas ke platform LoG+ dalam waktu H+2 pasca-event agar dapat diakses karyawan yang berhalangan hadir.',
      pic: 'Learning & Development',
      priority: 'MEDIUM'
    },
    {
      title: '3. Follow-up Community of Practice per Direktorat',
      desc: 'Bentuk grup diskusi tindak lanjut untuk mengaplikasikan wawasan program ke dalam rutinitas kerja sehari-hari.',
      pic: 'HRBP & Culture Champions',
      priority: 'HIGH PRIORITY'
    }
  ];

  actions.forEach((act, idx) => {
    const yP = 1.6 + idx * 1.65;
    slide6.addShape(pptx.shapes.ROUNDED_RECTANGLE, {
      x: 0.8,
      y: yP,
      w: 11.6,
      h: 1.45,
      fill: { color: CIMB_COLORS.lightGrey },
      line: { color: 'E2E8F0', width: 1 }
    });

    slide6.addText(act.title, { x: 1.1, y: yP + 0.15, w: 8.0, h: 0.35, fontSize: 13, bold: true, color: CIMB_COLORS.darkCharcoal, fontFace: 'Arial' });
    slide6.addText(act.desc, { x: 1.1, y: yP + 0.55, w: 8.0, h: 0.7, fontSize: 10, color: CIMB_COLORS.slateGrey, fontFace: 'Arial' });
    
    // Priority badge
    slide6.addShape(pptx.shapes.ROUNDED_RECTANGLE, {
      x: 9.6,
      y: yP + 0.25,
      w: 2.4,
      h: 0.4,
      fill: { color: act.priority.includes('HIGH') ? CIMB_COLORS.primaryRed : CIMB_COLORS.tealAccent }
    });
    slide6.addText(act.priority, { x: 9.6, y: yP + 0.25, w: 2.4, h: 0.4, fontSize: 9, bold: true, align: 'center', color: CIMB_COLORS.pureWhite, fontFace: 'Arial' });
    slide6.addText(`PIC: ${act.pic}`, { x: 9.4, y: yP + 0.75, w: 2.7, h: 0.4, fontSize: 9, align: 'center', color: CIMB_COLORS.slateGrey, fontFace: 'Arial' });
  });

  addFooter(slide6, 6);

  // Export to buffer / file
  const exportDir = path.join(__dirname, '..', 'exports');
  if (!fs.existsSync(exportDir)) {
    fs.mkdirSync(exportDir, { recursive: true });
  }

  const fileName = `PX_Report_${event.program_category}_${Date.now()}.pptx`;
  const filePath = path.join(exportDir, fileName);

  await pptx.writeFile({ fileName: filePath });
  return { fileName, filePath };
}

module.exports = {
  generateEventPPT
};
